apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagebox-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: messagebox
  template:
    metadata:
      labels:
        app: messagebox
    spec:
      containers:
        - name: messagebox
          image: messagebox:2.9
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          readinessProbe:
            exec:
              command:
                - /root/healthcheck
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: messagebox-service
spec:
  selector:
    app: messagebox
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
