apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagebox-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  replicas: 2
  selector:
    matchLabels:
      app: messagebox
  template:
    metadata:
      labels:
        app: messagebox
    spec:
      containers:
        - name: messagebox
          image: messagebox:2.7
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
          readinessProbe:
            exec:
              command:
                - /root/grpc_health_probe
                - -addr=:50051
            initialDelaySeconds: 5
            periodSeconds: 1

---
apiVersion: v1
kind: Service
metadata:
  name: messagebox-service
spec:
  selector:
    app: messagebox
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
