apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagebox-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messagebox
  template:
    metadata:
      labels:
        app: messagebox
    spec:
      containers:
        - name: messagebox
          image: messagebox:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051

---
apiVersion: v1
kind: Service
metadata:
  name: messagebox-service
spec:
  selector:
    app: messagebox
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
